apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-monitor
  namespace: monitoring
  labels: 
    level: system
spec:
  endpoints:
  - port: http-metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/version: 2.6.0
      app.kubernetes.io/component: exporter
