apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-export-monitor
  namespace: monitoring
  labels: 
    level: system
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      component: node-exporter
