apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gateway-monitor
  namespace: monitoring
  labels:
    level: system
spec:
  podMetricsEndpoints:
  - targetPort: 8001
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: admin-gateway-v24


