---
- name: install/configuration nginx
  hosts: node
  gather_facts: false
  become: yes
  tasks:
    - name: install nginx
      yum: 
        name: nginx
        state: present
    
    - name: configure nginx proxy 3000 port #Replace with a local configuration file
      copy:
        src: config/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
    
    - name: reload the nginx configuration
      shell: nginx & nginx -t && nginx -s reload
