on:
  push:
    branches:
      - "master"
name: Build Docker image and deploy for master or dev branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo $DOCKERHUB_USERNAME >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
