on:
  push:
    branches:
      - "master"
name: Build Docker image and deploy for master or dev branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Extract branch name
        shell: bash
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}
