name: Deploy OmniSAAS component to OmniSAAS
on:
  workflow_dispatch:
    inputs:
      customer:
        type: choice
        description: Chose your project.
        required: true
        options:
          - "-- Choose wisely --"
          - "bulgari"
          - "demo"
          - "swire"
          - "wiredcraft"
          - "zara"
          - "suitsupply"
          - "tiffany"
          - "lululemon"
      environment:
        type: choice
        description: Chose your ENV.
        required: true
        options:
          - "-- Choose wisely --"
          - dev
          - qa
          - staging
      component:
        type: choice
        description: Chose your component.
        required: true
        options:
          - "-- Choose wisely --"
          - admin-gateway
          - admin-gateway-v15
          - admin-gateway-v24
          - admin-ui
          - admin-ui-v2
          - automation
          - bulgari-wishlist-api
          - cms
          - contact
          - dmp
          - docs
          - events
          - events-organizer
          - form
          - gateway
          - gateway-v15
          - gateway-v24
          - group-booking
          - media
          - notification
          - suitsupply-notification
          - oidc-auth-proxy
          - oms
          - oms-app
          - "^ use for suitsupply, tiffany"
          - oms-ecom-v2
          - oms-event-v2
          - payment-gw
          - payment-gw-ecom
          - payment-gw-event
          - pcm-ecom
          - pcm-event
          - promotion
          - qr
          - static
          - screen-uploader
          - scrm
          - search
          - suitsupply-sfcc-connector
          - tag
          - tiffany-connector
          - tiffany-cdp-connector
          - tiffany-notification-report
          - tiffany-ecom-bff
          - tiffany-association
          - zara-instore-screen
          - video-sync
          - wechat-auth-proxy
          - wechat-connector
      version:
        type: string
        description: Type your version.
        required: true
      slack_mention:
        type: string
        description: Name of the mentioned user.
        required: false

permissions:
   contents: read

jobs:
  deploy:
    runs-on: cn
    env:
      playbook: "deploy.yml"
    defaults:
      run:
        working-directory: devops/ansible
    steps:
      - uses: actions/checkout@v3
      - uses: wiredcraft/github-actions/ansible/setup@master

      - name: setup kubectl
        uses: azure/setup-kubectl@v3
      
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.OMNISAAS_KUBECONFIG_NON_PROD }}
        
      - name: test the variables
        run: |
          echo ${{ input.customer }} ${{ input.environment }} ${{ input.component }} ${{ input.version }} echo ${{ env.playbook }}

      # - name: Deploy components
      #   env:
      #     ANSIBLE_STDOUT_CALLBACK: yaml
      #     PY_COLORS: '1'
      #     ANSIBLE_FORCE_COLOR: '1'
      #   run: |
      #       ansible-playbook -i inventories/${{ input.customer }}/${{ input.environment }} ${{ playbook }} \
      #       --vault-password-file /var/lib/pipelines/secure/omnisaas.key \
      #       -u wcladmin -b \
      #       -e "component_version=${{ input.version }}" \
      #       -e "@inventories/${{ input.customer }}/${{ input.environment}}/../versions.yml" \
      #       -e "component=${{ input.component }}"

      # - uses: Azure/k8s-deploy@v4
      #   with:
      #     namespace: monitoring
      #     manifests: |
      #       output

      # - name: Fix permissions
      #   if: always()
      #   run: sudo chown -R $(stat . -c %u:%g) output